### ISSUE TITLE
Does the Timeout Property Apply to the Client Instance Properly?

### ISSUE THREAD

**Issue by theyoung** [solacecommunity/solace-prometheus-exporter#62] opened 2023-12-21 05:14 UTC
I'm interested in knowing whether the timeout property in the Solace configuration file, solace_prometheus_exporter.ini, is correctly applied to the client instance.

In solace_prometheus_exporter.go from the Solace Prometheus Exporter repository, there is a code snippet that sets the conf.Timeout value to 2s, overriding any timeout value specified in the configuration file.

solace_prometheus_exporter.go
https://github.com/solacecommunity/solace-prometheus-exporter/blob/e8b1054d27de4d48beb86fd78918c50817da73ad/solace_prometheus_exporter.go#L94C1-L103C76
```
	// Test scrape to check if broker can be accessed. If it fails it prints a warn to the log file.
	// Note that failure is not fatal, as broker might not have started up yet.
	conf.Timeout, _ = time.ParseDuration("2s") // Don't delay startup too much
```

This code forces clients to change the conf.Timeout value to 2s, regardless of the timeout value set up in the configuration file.

This value is then applied in the doHandle method and the newHttpClient method.

- doHandle: 
https://github.com/solacecommunity/solace-prometheus-exporter/blob/e8b1054d27de4d48beb86fd78918c50817da73ad/solace_prometheus_exporter.go#L255

- newHttpClient: 
https://github.com/solacecommunity/solace-prometheus-exporter/blob/e8b1054d27de4d48beb86fd78918c50817da73ad/exporter/config.struct.go#L175
 
Please confirm that the timeout configuration value will effectively be applied to the client instance when creating a connection to the broker.

**Comment by GreenRover** [comment] 2023-12-21 05:20
Currently it is not OK.
I found it by my self.
It is already fixed in „testing“ build.

**Comment by theyoung** [comment] 2023-12-21 05:46
@GreenRover  Thank you so much for your help. When I find any abnormal behavior from the branch code, I'll let you know.

**Comment by GreenRover** [comment] 2024-02-10 13:38
i close this issue caused by in activity on your side.

**Closed by GreenRover** 2024-02-10 13:38 UTC
